In [1]:
import otter
grader = otter.Notebook()
'grader defined'

'grader defined'

# Homework 2: Arrays and Tables

In [2]:
# Don't change this cell; just run it.
# When you log-in please hit return (not shift + return) after typing in your email
import numpy as np
from datascience import *


**Recommended Reading**: 
* [Data Types](https://inferentialthinking.com/chapters/04/Data_Types.html) 
* [Sequences](https://www.inferentialthinking.com/chapters/05/Sequences.html)

Please complete this notebook by filling in the cells provided.

This assignment is due by **11:59pm on the due date listed in Canvas**. Late work will not be accepted as per the course policies. 
 
Throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook! For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. 

<font color="#E74C3C">**Important**: In this homework, the `grader.check()` tests will no longer tell you if your answers are correct, only if your answer could be correct (of the correct type, format, etc...).</font>

Remember to save and checkpoint this file when you have completed it and to submit it to Canvas.

## 1. Creating Arrays


**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `math` module.

*Note:* Python lists are different/behave differently than numpy arrays. In DSCI 101, we use numpy arrays, so please make an **array**, not a python list.

<!--
BEGIN QUESTION
name: q1_1
-->

In [5]:
# Our solution involved one extra line of code before creating
# weird_numbers.
import math
weird_numbers = make_array(-2,math.sin(1.2),3,5**math.cos(1.2))
weird_numbers

array([-2.        ,  0.93203909,  3.        ,  1.79174913])

In [4]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

<!--
BEGIN QUESTION
name: q1_2
-->

In [6]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

In [7]:
grader.check("q1_2")

q1_2 results: All test cases passed!

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string.

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

<!--
BEGIN QUESTION
name: q1_3
-->

In [9]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


In [10]:
grader.check("q1_3")

q1_3 results: All test cases passed!

## 2. Indexing Arrays


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0. Please don't use bracket notation when indexing (i.e. `arr[0]`), as this can yield different data type outputs than what we will be expecting. This can cause you to fail an autograder test.

*Note:* In some cases we will be creating objects or reading in data for you using tables, but you'll learn to work with tables yourself next week. 

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

<!--
BEGIN QUESTION
name: q2_1
-->

In [36]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = int(some_numbers[2])
third_element

-6

In [37]:
grader.check("q2_1")

q2_1 results: All test cases passed!

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information (the cells that say "Ellipsis") by assigning `blank_a`, `blank_b`, `blank_c`, and `blank_d` to the correct elements in the table.

<!--
BEGIN QUESTION
name: q2_2
-->

In [14]:
blank_a = some_numbers[2]
blank_b = some_numbers[3]
blank_c = 0
blank_d = 3
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", blank_a, blank_b, "fifth"),
    "Index",                     make_array(blank_c, 1, 2, blank_d, 4),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
-6                        | 2     | -6
-10                       | 3     | -10
fifth                     | 4     | -15

In [15]:
grader.check("q2_2")

q2_2 results: All test cases passed!

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

<!--
BEGIN QUESTION
name: q2_3
-->

In [16]:
index_of_last_element = len(some_numbers) - 1

In [17]:
grader.check("q2_3")

q2_3 results: All test cases passed!

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  Calling `.column(...)` on a table returns an array of the column specified, in this case the `Birth Year` column of the `president_births` table. The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

<!--
BEGIN QUESTION
name: q2_4
-->

In [34]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = int(president_birth_years[-1])
most_recent_birth_year

1917

In [35]:
grader.check("q2_4")

q2_4 results: All test cases passed!

**Question 5.** Finally, assign `sum_of_birth_years` to the sum of the first, tenth, and last birth year in `president_birth_years`.

<!--
BEGIN QUESTION
name: q2_5
-->

In [32]:
sum_of_birth_years = int(president_birth_years[0] + president_birth_years[9] + president_birth_years[len(president_birth_years)-1])
sum_of_birth_years

5433

In [33]:
grader.check("q2_5")

q2_5 results: All test cases passed!

## 3. Basic Array Arithmetic


**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157. Assign each variable below such that `first_product` is assigned to the result of $42 * 157$, `second_product` is assigned to the result of $4224 * 157$, and so on. 

For this question, **don't** use arrays.

<!--
BEGIN QUESTION
name: q3_1
-->

In [38]:
first_product = 42 * 157
second_product = 4224
third_product = 42422424
fourth_product = -250
print(first_product, second_product, third_product, fourth_product)

6594 4224 42422424 -250


In [39]:
grader.check("q3_1")

q3_1 results: All test cases passed!

**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

<!--
BEGIN QUESTION
name: q3_2
-->

In [44]:
numbers = make_array(42, 4224, 42422424, -250)
products = numbers * 157
products

array([      6594,     663168, 6660320568,     -39250])

In [45]:
grader.check("q3_2")

q3_2 results: All test cases passed!

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the correct products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

<!--
BEGIN QUESTION
name: q3_3
-->

In [46]:
correct_products = numbers * 1577
correct_products

array([      66234,     6661248, 66900162648,     -394250])

In [47]:
grader.check("q3_3")

q3_3 results: All test cases passed!

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](https://www.noaa.gov/), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Make sure to **ROUND** the final result after converting to Celsius to the nearest integer using the `np.round` function.

<!--
BEGIN QUESTION
name: q3_4
-->

In [50]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = np.round((max_temperatures - 32) * 5/9)
celsius_max_temperatures

array([-4., 31., 32., ..., 17., 23., 16.], shape=(65000,))

In [51]:
grader.check("q3_4")

q3_4 results: All test cases passed!

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Pay attention to the units, give your answer in Celsius!** Make sure **NOT** to round your answer for this question!

<!--
BEGIN QUESTION
name: q3_5
-->

In [54]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = np.round(((max_temperatures - min_temperatures)-32)* 5/9)
                              
celsius_temperature_ranges

array([-11.,  -8.,  -6., ...,  -1.,  -6.,  -7.], shape=(65000,))

In [55]:
grader.check("q3_5")

q3_5 results: All test cases passed!

## 4. World Population


Remember that the tests from this point on will **not** necessarily tell you whether or not your answers are correct.

The cell below loads a table of estimates of the world population for different years, starting in 1950. The estimates come from the [US Census Bureau website](https://www.census.gov/en.html).

In [56]:
world = Table.read_table("world_population.csv").select('Year', 'Population')
world.show(4)

The name `population` is assigned to an array of population estimates.

In [57]:
population = world.column(1)
population

array([2557628654, 2594939877, 2636772306, 2682053389, 2730228104,
       2782098943, 2835299673, 2891349717, 2948137248, 3000716593,
       3043001508, 3083966929, 3140093217, 3209827882, 3281201306,
       3350425793, 3420677923, 3490333715, 3562313822, 3637159050,
       3712697742, 3790326948, 3866568653, 3942096442, 4016608813,
       4089083233, 4160185010, 4232084578, 4304105753, 4379013942,
       4451362735, 4534410125, 4614566561, 4695736743, 4774569391,
       4856462699, 4940571232, 5027200492, 5114557167, 5201440110,
       5288955934, 5371585922, 5456136278, 5538268316, 5618682132,
       5699202985, 5779440593, 5857972543, 5935213248, 6012074922,
       6088571383, 6165219247, 6242016348, 6318590956, 6395699509,
       6473044732, 6551263534, 6629913759, 6709049780, 6788214394,
       6866332358, 6944055583, 7022349283, 7101027895, 7178722893,
       7256490011])

In this question, you will apply some built-in Numpy functions to this array. Numpy is a module that is often used in Data Science!

<img src="array_diff.png" style="width: 600px;"/>

The difference function `np.diff` subtracts each element in an array from the element after it within the array. As a result, the length of the array `np.diff` returns will always be one less than the length of the input array.

<img src="array_cumsum.png" style="width: 700px;"/>

The cumulative sum function `np.cumsum` outputs an array of partial sums. For example, the third element in the output array corresponds to the sum of the first, second, and third elements.

**Question 1.** Very often in data science, we are interested understanding how values change with time. Use `np.diff` and `np.max` (or just `max`) to calculate the largest annual change in population between any two consecutive years.

<!--
BEGIN QUESTION
name: q4_1
-->

In [60]:
largest_population_change = int(np.max(np.diff(population)))
largest_population_change

87515824

In [61]:
grader.check("q4_1")

q4_1 results: All test cases passed!

**Question 2.** What do the values in the resulting array represent (choose one)?

In [62]:
np.cumsum(np.diff(population))

array([  37311223,   79143652,  124424735,  172599450,  224470289,
        277671019,  333721063,  390508594,  443087939,  485372854,
        526338275,  582464563,  652199228,  723572652,  792797139,
        863049269,  932705061, 1004685168, 1079530396, 1155069088,
       1232698294, 1308939999, 1384467788, 1458980159, 1531454579,
       1602556356, 1674455924, 1746477099, 1821385288, 1893734081,
       1976781471, 2056937907, 2138108089, 2216940737, 2298834045,
       2382942578, 2469571838, 2556928513, 2643811456, 2731327280,
       2813957268, 2898507624, 2980639662, 3061053478, 3141574331,
       3221811939, 3300343889, 3377584594, 3454446268, 3530942729,
       3607590593, 3684387694, 3760962302, 3838070855, 3915416078,
       3993634880, 4072285105, 4151421126, 4230585740, 4308703704,
       4386426929, 4464720629, 4543399241, 4621094239, 4698861357])

1) The total population change between consecutive years, starting at 1951.

2) The total population change between 1950 and each later year, starting at 1951.

3) The total population change between 1950 and each later year, starting inclusively at 1950.

<!--
BEGIN QUESTION
name: q4_2
-->

In [64]:
# Assign cumulative_sum_answer to 1, 2, or 3
cumulative_sum_answer = int(1)

In [65]:
grader.check("q4_2")

q4_2 results: All test cases passed!

## 5. Old Faithful


Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

<!--
BEGIN QUESTION
name: q5_1
-->

In [70]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = int(min(waiting_times))
longest = int(max(waiting_times))
average = int(np.mean(waiting_times))

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 70 minutes on average.


In [71]:
grader.check("q5_1")

q5_1 results: All test cases passed!

**Question 2.** Assign `biggest_decrease` to the biggest decrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. 

*Hint 1*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/05/1/Arrays.html#Functions-on-Arrays). You have also seen this function earlier in the homework!

*Hint 2*: We want to return the absolute value of the biggest decrease.

<!--
BEGIN QUESTION
name: q5_2
-->

In [100]:
biggest_decrease = int(abs(min(np.diff(waiting_times))))
biggest_decrease

45

In [101]:
grader.check("q5_2")

q5_2 results: All test cases passed!

**Question 3.** If you expected Old Faithful to erupt every hour, you would expect to wait a total of `60 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the expected and actual total amount of waiting time to see the first `i+1` eruptions. 

*Hint*: You'll need to compare a cumulative sum to a range.

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

<!--
BEGIN QUESTION
name: q5_3
-->

In [102]:
difference_from_expected = np.abs(np.cumsum(waiting_times) - 60 * np.arange(1, len(waiting_times) + 1))
difference_from_expected

array([  19,   13,   27,   29,   54,   49,   77,  102,   93,  118,  112,
        136,  154,  141,  164,  156,  158,  182,  174,  193,  184,  171,
        189,  198,  212,  235,  230,  246,  264,  283,  296,  313,  319,
        339,  353,  345,  333,  353,  352,  382,  402,  400,  424,  422,
        435,  458,  462,  455,  477,  476,  491,  521,  515,  535,  529,
        552,  563,  567,  584,  605,  604,  628,  616,  638,  638,  670,
        688,  706,  711,  724,  746,  742,  761,  772,  774,  790,  790,
        808,  824,  847,  862,  884,  894,  899,  912,  940,  956,  976,
        964,  990,  990, 1020, 1010, 1028, 1031, 1043, 1067, 1082, 1073,
       1095, 1097, 1125, 1114, 1137, 1158, 1145, 1169, 1161, 1187, 1208,
       1223, 1222, 1251, 1270, 1269, 1290, 1280, 1305, 1304, 1331, 1324,
       1333, 1350, 1346, 1374, 1395, 1380, 1402, 1397, 1427, 1412, 1435,
       1431, 1460, 1446, 1468, 1459, 1485, 1478, 1497, 1518, 1518, 1540,
       1557, 1573, 1572, 1592, 1581, 1617, 1610, 16

In [103]:
grader.check("q5_3")

q5_3 results: All test cases passed!

**Question 4.** Let’s imagine your guess for the next wait time was always just the length of the previous waiting time. If you always guessed the previous waiting time, how big would your error in guessing the waiting times be, on average?

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

<!--
BEGIN QUESTION
name: q5_4
-->

In [106]:
average_error = int(np.mean(np.abs(waiting_times[1:] - waiting_times[:-1])))
average_error

20

In [107]:
grader.check("q5_4")

q5_4 results: All test cases passed!

You're done with HW 2! Be sure to run the tests and verify that they all pass, then **Save** your changes, then **Download** your file to your host machine (if you are using jupyterhub), then submit your file to the HW2 assignment in **Canvas** by 11:59pm on the due date.